"""Generate a MANIFEST.md with SHA-256 of every code/doc file in the package.

Run after every release to produce a tamper-evident manifest. Anyone can
verify their copy matches by running:

    python -m scripts.generate_manifest --check

Usage:
    python -m scripts.generate_manifest                # generate
    python -m scripts.generate_manifest --check        # verify against existing
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Iterable


# Files included in manifest (everything that defines behavior + docs)
INCLUDE_PATTERNS = [
    "aion_nexus/**/*.py",
    "server/**/*.py",
    "tests/**/*.py",
    "scripts/**/*.py",
    "examples/**/*.py",
    "*.md",
    "docs/**/*.md",
    "Dockerfile",
    "docker-compose.yml",
    "pyproject.toml",
    "requirements.txt",
    "requirements-dev.txt",
    "Makefile",
    ".pre-commit-config.yaml",
    ".github/**/*.yml",
]

EXCLUDE_PATTERNS = [
    "**/__pycache__/**",
    "**/.pytest_cache/**",
    "**/.ruff_cache/**",
    "**/*.pyc",
    "checkpoints/**",
    "data/**",
    ".venv/**",
]


def iter_files(root: Path) -> Iterable[Path]:
    seen = set()
    for pattern in INCLUDE_PATTERNS:
        for p in root.glob(pattern):
            if not p.is_file():
                continue
            rel = p.relative_to(root)
            if any(rel.match(ex) for ex in EXCLUDE_PATTERNS):
                continue
            if rel in seen:
                continue
            seen.add(rel)
            yield p


def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def build_manifest(root: Path) -> list[dict]:
    entries = []
    for f in sorted(iter_files(root)):
        rel = f.relative_to(root)
        entries.append({
            "path": str(rel).replace("\\", "/"),
            "size": f.stat().st_size,
            "sha256": sha256_of(f),
        })
    return entries


def write_manifest(entries: list[dict], out: Path) -> None:
    lines = [
        "# Manifest — AION-NEXUS",
        "",
        "Tamper-evident manifest of all code and documentation in this package.",
        "Generated by `python -m scripts.generate_manifest`.",
        "",
        "Verify: `python -m scripts.generate_manifest --check`",
        "",
        f"Total files: {len(entries)}",
        f"Total size: {sum(e['size'] for e in entries) / 1024:.1f} KB",
        "",
        "| Path | Size (B) | SHA-256 |",
        "|---|---|---|",
    ]
    for e in entries:
        lines.append(f"| `{e['path']}` | {e['size']} | `{e['sha256']}` |")
    out.write_text("\n".join(lines) + "\n")


def check_manifest(entries_now: list[dict], manifest_path: Path) -> int:
    if not manifest_path.exists():
        print(f"ERROR: manifest not found at {manifest_path}")
        return 2

    txt = manifest_path.read_text()
    # Parse table rows
    expected = {}
    for line in txt.splitlines():
        if line.startswith("| `") and "|" in line[3:]:
            parts = [p.strip() for p in line.strip("|").split("|")]
            if len(parts) >= 3:
                path = parts[0].strip("`")
                sha = parts[2].strip("`")
                expected[path] = sha

    diffs = []
    for e in entries_now:
        path = e["path"]
        if path not in expected:
            diffs.append(("ADDED", path, e["sha256"]))
        elif expected[path] != e["sha256"]:
            diffs.append(("MODIFIED", path, e["sha256"]))

    paths_now = {e["path"] for e in entries_now}
    for path in expected:
        if path not in paths_now:
            diffs.append(("DELETED", path, ""))

    if not diffs:
        print(f"OK: all {len(entries_now)} files match manifest.")
        return 0

    print(f"DIFFERENCES ({len(diffs)}):")
    for kind, path, sha in diffs:
        print(f"  {kind:10s}  {path}")
    return 1


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".")
    parser.add_argument("--out", default="MANIFEST.md")
    parser.add_argument("--check", action="store_true",
                        help="Verify current state matches existing MANIFEST.md")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    entries = build_manifest(root)

    if args.check:
        return check_manifest(entries, root / args.out)

    write_manifest(entries, root / args.out)
    print(f"Wrote {root / args.out} with {len(entries)} entries.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
